---
name: "Listen URL"
guid: "f7f33b15-a6cf-42a7-813d-169f458cf6e0"
version: "0.1.0.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "Provide simple /listen URLs for audio streams"
description: >
  Changes the URL copied from the **Copy Stream** button to a
  short `/listen/<item_id>` format. Requires using a reverse
  proxy to handle the `/listen` endpoint.
category: "General"
owner: "jellyfin"
artifacts:
- "Jellyfin.Plugin.ListenUrl.dll"
changelog: >
  Initial release
